services:
  whatweb:
    image: whatweb
    container_name: whatweb
    # Standard-Argumente (werden an ENTRYPOINT ["whatweb"] angeh√§ngt)
    command: ["-v", "-a", "3", "https://example.com"]
    volumes:
      - ./data:/data
    restart: "no"
